import type { AppData, BugFixDetails, ChecklistItem, CreativeBrief, EffectType, HookupDetails, OptimizationDetails, Reflection, ResearchDetails, RequirementBreakdown, Submission, Task, TaskFamily, TaskTemplate, TestingInstructions, WorkLog } from './types'
import { ensureWorkPage } from './workPageModel'

export const nowIso = () => new Date().toISOString()
export const makeId = (prefix: string) => `${prefix}-${Math.random().toString(36).slice(2, 8)}-${Date.now().toString(36).slice(-4)}`
export const buildJiraLink = (_id: string) => ''

export const defaultRequirements = (overrides: Partial<RequirementBreakdown> = {}): RequirementBreakdown => ({
  gameplayPurpose: '', playerUnderstanding: '', triggerCondition: '', startEvent: '', endEvent: '', duration: '', location: '', viewingDistance: '', visibility: 'Third-person', repeatability: 'Repeatable', maxSimultaneous: '', requiredStates: [], existingReference: '', technicalConstraints: '', performanceConcerns: '', dependencies: '', missingInfo: [], ...overrides,
})

export const defaultTesting = (overrides: Partial<TestingInstructions> = {}): TestingInstructions => ({ consoleCommand: '', mapLocation: '', triggerMethod: '', requiredWeapon: '', gameplaySetup: '', knownIssue: '', ...overrides })

export const defaultTestingChecklist = (extra: string[] = []): ChecklistItem[] => [
  'Confirm the effect triggers', 'Confirm the effect resets correctly', 'Confirm timing matches gameplay', 'Test normal gameplay distance', 'Test repeated triggering', 'Check low and high graphics settings', 'Capture a review video', ...extra,
].map((label, index) => ({ id: `test-${index}-${label}`, label, done: false }))

export const defaultSubmissionChecklist = (labels?: string[]): ChecklistItem[] => (labels ?? ['Latest files synced', 'No accidental files included', 'Asset names checked', 'Effect triggers correctly', 'Reset tested', 'Performance checked', 'Latest feedback addressed', 'Video captured']).map((label, index) => ({ id: `submission-${index}-${label}`, label, done: false }))

export const defaultSubmission = (overrides: Partial<Submission> = {}): Submission => ({ changelist: '', description: '', filesChanged: '', relatedJira: '', buildTested: '', testResult: '', limitations: '', reviewers: '', status: 'Not ready', checklist: defaultSubmissionChecklist(), ...overrides })

export const defaultReflection = (overrides: Partial<Reflection> = {}): Reflection => ({ completed: false, completedAt: '', worked: '', difficult: '', nextTime: '', finalResult: '', gameplayGoal: '', feedbackImproved: '', processSlow: '', missingAtStart: '', dependencyFriction: '', avoidableRework: '', artisticQuality: '', referenceTechnique: '', morePolish: '', technicalUseful: '', technicalLimitation: '', reusable: '', communication: '', reusableAsset: '', reusableSetup: '', reusableMessage: '', reusableTesting: '', futureToolIdea: '', growthAction: '', tags: [], ...overrides })

export const defaultCreativeBrief = (overrides: Partial<CreativeBrief> = {}): CreativeBrief => ({ gameplayPurpose: '', playerUnderstanding: '', visualDirection: '', referenceLinks: '', trigger: '', requiredStates: '', duration: '', location: '', viewingDistance: '', dependencies: '', technicalConstraints: '', performanceConcerns: '', ...overrides })
export const defaultBugFix = (overrides: Partial<BugFixDetails> = {}): BugFixDetails => ({ observedBehavior: '', expectedBehavior: '', severity: 'Normal', frequency: '', firstObservedBuild: '', currentBuild: '', evidenceLink: '', reproductionMap: '', reproductionLocation: '', triggerMethod: '', requiredItem: '', dvar: '', reproductionSteps: [], reproductionResult: '', suspectedSystem: 'Unknown', investigationNotes: '', relatedOwner: '', previousWorkingCl: '', relatedTasks: '', fixAttempts: [], rootCause: '', fixSummary: '', verificationSteps: '', verifiedBuild: '', regressionRisk: '', followUpNeeded: '', finalStatus: '', ...overrides })
export const defaultOptimization = (overrides: Partial<OptimizationDetails> = {}): OptimizationDetails => ({ performanceConcern: '', targetPlatform: '', graphicsSetting: '', maxInstances: '', gameplayDistance: '', currentIssue: '', beforeParticleCount: '', beforeEmitterCount: '', beforeMaterialComplexity: '', beforeFrameNote: '', beforeCaptureLink: '', changes: '', afterMetrics: '', visualDifference: '', gameplayReadability: '', remainingLimitation: '', comparisonCapture: '', verification: '', ...overrides })
export const defaultHookup = (overrides: Partial<HookupDetails> = {}): HookupDetails => ({ gameplayEventName: '', scriptableName: '', vfxAsset: '', triggerOwner: '', requiredStates: '', modelDependency: '', animationDependency: '', sfxDependency: '', eventTiming: '', resetBehavior: '', testingInstructions: '', currentStatus: '', blocker: '', verification: '', ...overrides })
export const defaultResearch = (overrides: Partial<ResearchDetails> = {}): ResearchDetails => ({ question: '', productionProblem: '', hypothesis: '', reference: '', experiment: '', result: '', limitations: '', reusableOutput: '', possibleProductionUse: '', nextExperiment: '', ...overrides })

const historyEntry = (label: string, detail: string, at: string) => ({ id: makeId('history'), type: 'Status' as const, label, detail, at })

const baseTask = (overrides: Partial<Task>): Task => {
  const createdAt = overrides.createdAt ?? nowIso()
  const updatedAt = overrides.updatedAt ?? createdAt
  const task: Task = {
    id: overrides.id ?? makeId('task'), name: overrides.name ?? 'Untitled demo task', feature: overrides.feature ?? '', mapMode: overrides.mapMode ?? '', jira: overrides.jira ?? '', source: overrides.source ?? 'Public demo', requestingDiscipline: overrides.requestingDiscipline ?? 'Design', requester: overrides.requester ?? '', priority: overrides.priority ?? 'Normal', workType: overrides.workType ?? 'New VFX', effectType: overrides.effectType ?? 'Other', tags: overrides.tags ?? [], lifecycle: overrides.lifecycle ?? 'Active', pinned: overrides.pinned ?? false, lastOpenedAt: overrides.lastOpenedAt ?? updatedAt, archivedAt: overrides.archivedAt ?? '', familyId: overrides.familyId ?? '', relationships: overrides.relationships ?? [], pipelineIds: overrides.pipelineIds ?? [], variationDecision: overrides.variationDecision, targetDate: overrides.targetDate ?? '', rawRequest: overrides.rawRequest ?? '', requirements: overrides.requirements ?? defaultRequirements(), stage: overrides.stage ?? 'New Request', visualDirection: overrides.visualDirection ?? '', nextAction: overrides.nextAction ?? 'Define the first useful pass.', blocker: overrides.blocker ?? '', people: overrides.people ?? [], links: overrides.links ?? [], keyRequirements: overrides.keyRequirements ?? [], openQuestions: overrides.openQuestions ?? [], latestFeedback: overrides.latestFeedback ?? '', latestChangelist: overrides.latestChangelist ?? '', createdAt, updatedAt, workLogs: overrides.workLogs ?? [], feedback: overrides.feedback ?? [], testing: overrides.testing ?? defaultTestingChecklist(), testingInstructions: overrides.testingInstructions ?? defaultTesting(), submission: overrides.submission ?? defaultSubmission(), impactTags: overrides.impactTags ?? [], followUps: overrides.followUps ?? [], reflection: overrides.reflection ?? defaultReflection(), creativeBrief: overrides.creativeBrief ?? defaultCreativeBrief(), bugFix: overrides.bugFix ?? defaultBugFix(), optimization: overrides.optimization ?? defaultOptimization(), hookup: overrides.hookup ?? defaultHookup(), research: overrides.research ?? defaultResearch(), leanCanvas: overrides.leanCanvas ?? {}, detailPreferences: overrides.detailPreferences ?? { visibleSections: [], hiddenSections: [], collapsedSections: [], order: [] }, history: overrides.history ?? [historyEntry(`Created in ${overrides.stage ?? 'New Request'}`, 'Demo task added to this browser.', createdAt)],
  }
  return { ...task, ...overrides }
}

const normalizeTask = (raw: Partial<Task>): Task => {
  const task = baseTask({ ...raw, requirements: defaultRequirements(raw.requirements ?? {}), testingInstructions: defaultTesting(raw.testingInstructions ?? {}), submission: defaultSubmission(raw.submission ?? {}), reflection: defaultReflection(raw.reflection ?? {}), creativeBrief: defaultCreativeBrief(raw.creativeBrief ?? {}), bugFix: defaultBugFix(raw.bugFix ?? {}), optimization: defaultOptimization(raw.optimization ?? {}), hookup: defaultHookup(raw.hookup ?? {}), research: defaultResearch(raw.research ?? {}) })
  return ensureWorkPage({ ...task, tags: Array.isArray(raw.tags) ? raw.tags : [], workLogs: Array.isArray(raw.workLogs) ? raw.workLogs as WorkLog[] : [], feedback: Array.isArray(raw.feedback) ? raw.feedback : [], followUps: Array.isArray(raw.followUps) ? raw.followUps : [], history: Array.isArray(raw.history) ? raw.history : task.history, relationships: Array.isArray(raw.relationships) ? raw.relationships : [], pipelineIds: Array.isArray(raw.pipelineIds) ? raw.pipelineIds : [] })
}

const publicFamily: TaskFamily = { id: 'family-demo', name: 'Demo Interaction Set', featureOrMap: 'Training Range', description: 'Generic examples for exploring the workflow.', sharedTags: ['Energy', 'Timing'], sharedReferences: [], sharedAssetLinks: [], sharedPipelineLinks: ['pipeline-demo'], sharedTestingInstructions: 'Test the trigger, reset, readability, and repeat behavior.', sharedDependencies: 'Gameplay event and VFX asset', notes: 'Public demo context only.', reusableLessons: ['Ask one focused review question at a time.'], createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' }
const publicPipeline = { id: 'pipeline-demo', name: 'Readable Gameplay Effect', purpose: 'A generic flow from trigger through review and handoff.', workTypes: ['New VFX', 'Iteration / Polish', 'Optimization'] as Task['workType'][], effectTypes: ['Charge-up', 'Gameplay Feedback', 'Other'] as EffectType[], requiredAssetsSystems: 'Gameplay event, VFX asset, test location', setupSteps: ['Confirm the trigger.', 'Capture the first readable pass.', 'Test at gameplay distance.'], eventNames: ['On activate', 'On complete', 'On reset'], commonControls: 'Timing, scale, visibility, intensity', testingInstructions: 'Trigger, interrupt, repeat, and observe at intended distance.', knownLimitations: 'Generic demo data has no connected tools.', commonFailureCases: 'Unclear trigger, weak read, missing reset.', reusableNotes: 'Keep the next action small.', reusableLessons: ['Record the answer and the decision separately.'], relatedTaskIds: ['demo-charge', 'demo-optimization'], tags: ['Timing', 'Gameplay'], createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' }

const demoCharge = baseTask({ id: 'demo-charge', name: 'Orbital Beacon Charge', feature: 'Orbital Beacon', mapMode: 'Training Range', source: 'Public demo', priority: 'Normal', workType: 'New VFX', effectType: 'Charge-up', tags: ['Energy', 'Timing'], familyId: publicFamily.id, pipelineIds: [publicPipeline.id], stage: 'Iterating', nextAction: 'Check the buildup read at normal gameplay distance.', rawRequest: 'Create a readable charge-up that confirms the beacon is ready to activate.', requirements: defaultRequirements({ gameplayPurpose: 'Confirm the beacon is ready.', playerUnderstanding: 'The beacon is charging toward activation.', triggerCondition: 'Player activates beacon', duration: '1.2s', location: 'Beacon platform', viewingDistance: '10–25m', requiredStates: ['Idle', 'Buildup', 'Complete', 'Reset'] }), leanCanvas: { intendedRead: 'The beacon is charging toward activation.', visualDirection: 'Layered energy rings with a clear full-charge beat.', currentPass: 'First readable pass captured.', openQuestion: 'Does the charge start early enough?' }, testingInstructions: defaultTesting({ mapLocation: 'Training Range', triggerMethod: 'Activate the beacon' }), feedback: [{ id: 'demo-feedback', requestedFrom: 'Reviewer', discipline: 'Design', dateRequested: '2026-01-02', build: '', previewLink: '', changed: 'Adjusted the charge timing.', question: 'Does the charge read clearly before activation?', status: 'Waiting', response: '', decision: '', followUp: '' }] })
const demoOptimization = baseTask({ id: 'demo-optimization', name: 'Beacon Smoke Optimization', feature: 'Orbital Beacon', mapMode: 'Training Range', source: 'Public demo', priority: 'Normal', workType: 'Optimization', effectType: 'Gameplay Feedback', tags: ['Performance', 'Smoke'], familyId: publicFamily.id, pipelineIds: [publicPipeline.id], stage: 'Ready to Submit', nextAction: 'Review the before/after capture.', optimization: defaultOptimization({ performanceConcern: 'Reduce supporting smoke cost while preserving the read.', changes: 'Reduced supporting smoke count.', visualDifference: 'The activation read remains clear.', remainingLimitation: 'Capture a side-by-side comparison.', verification: 'Check normal distance and low graphics settings.' }), leanCanvas: { goal: 'Reduce supporting smoke cost.', changes: 'Reduced supporting smoke count.', result: 'Activation remains readable.', remainingConcern: 'Capture a side-by-side comparison.' }, submission: defaultSubmission({ status: 'Ready to submit' }) })

export const initialData: AppData = { dataVersion: 4, tasks: [demoCharge, demoOptimization], templates: [{ id: 'template-demo', name: 'Gameplay charge-up', description: 'A compact generic starting point for a readable effect.', requiredStates: ['Idle', 'Buildup', 'Complete', 'Reset'], requirementQuestions: ['What should the player understand?', 'When must the read begin?'], feedbackQuestions: ['Does the timing read clearly?'], impactTags: ['Timing changed', 'Performance checked'], submissionChecklist: ['Effect triggers correctly', 'Reset tested', 'Performance checked'], commonTags: ['Timing', 'Gameplay'], workType: 'New VFX', effectType: 'Charge-up', pipelineId: publicPipeline.id }], focusTaskIds: ['demo-charge'], savedViews: [], recentFilters: [], pinnedTaskIds: ['demo-charge'], recentTaskIds: ['demo-charge', 'demo-optimization'], taskViewState: {}, families: [publicFamily], pipelines: [publicPipeline], promotedLessons: [], preferences: { autoArchiveDays: 0, taskPageDensity: 'Lean', defaultTaskTab: 'Overview' } }

export const migrateAppData = (raw: unknown): AppData => {
  if (!raw || typeof raw !== 'object') return initialData
  const value = raw as Partial<AppData>
  const tasks = Array.isArray(value.tasks) && value.tasks.length ? value.tasks.map((task) => normalizeTask(task)) : initialData.tasks
  return { dataVersion: 4, tasks, templates: Array.isArray(value.templates) && value.templates.length ? value.templates : initialData.templates, focusTaskIds: Array.isArray(value.focusTaskIds) ? value.focusTaskIds : [], savedViews: Array.isArray(value.savedViews) ? value.savedViews : [], recentFilters: Array.isArray(value.recentFilters) ? value.recentFilters : [], pinnedTaskIds: Array.isArray(value.pinnedTaskIds) ? value.pinnedTaskIds : [], recentTaskIds: Array.isArray(value.recentTaskIds) ? value.recentTaskIds : [], taskViewState: value.taskViewState ?? {}, customWorkTypes: value.customWorkTypes ?? [], customEffectTypes: value.customEffectTypes ?? [], families: Array.isArray(value.families) ? value.families : initialData.families, pipelines: Array.isArray(value.pipelines) ? value.pipelines : initialData.pipelines, promotedLessons: Array.isArray(value.promotedLessons) ? value.promotedLessons : [], preferences: { autoArchiveDays: value.preferences?.autoArchiveDays === 30 || value.preferences?.autoArchiveDays === 60 || value.preferences?.autoArchiveDays === 90 ? value.preferences.autoArchiveDays : 0, taskPageDensity: value.preferences?.taskPageDensity === 'Detailed' ? 'Detailed' : 'Lean', defaultTaskTab: value.preferences?.defaultTaskTab === 'Work Page' ? 'Work Page' : 'Overview' } }
}
